services:
  skillshare:
    image: postgres
    container_name: skillshare
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: skillshare
  
  frontend:
    build:
      context: ../skill-share-frontend/
      dockerfile: Dockerfile
    container_name: "skill-share_frontend"
    ports:
      - "5173:5173"
    volumes:
      - ../skill-skare-frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - catcollectorspa

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_api
    command: >
      bash -c "
              python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/backend/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - ShareSkill
volumes:
  postgres_data: